### ISSUE TITLE
[Symfony-toggle] Set strategy and segment type fields as mandatory

### ISSUE THREAD

**Issue by xserrat** [pheature-flags/pheature-flags#197]
Epic: #97 Symfony Toggle
Package: https://github.com/pheature-flags/symfony-toggle

As commented in the #176 , we have to add the following strategy and segment type fields as mandatory:
* Strategy type: `type` and `factory_id`
* Segment type: `type` and `factory_id`

Check out the documentation for that [here](https://symfony.com/doc/current/components/config/definition.html#default-and-required-values) and add the corresponding tests.

```yaml
pheature_flags:
      strategy_types:
           - { type: 'a_type' } # <--- Here this config needs the `factory_id` in order to instantiate the Strategy so the config should fail
```

> We could add it using this nomenclature. What do you think?

@xserrat Yes, we must validate it ;-D, we can create another task for it.

_Originally posted by @kpicaza in https://github.com/pheature-flags/pheature-flags/issues/196#issuecomment-834368818_
