### ISSUE TITLE
Create a Symfony Toggle Bundle Package

### ISSUE THREAD

**Issue by kpicaza** [pheature-flags/pheature-flags#97]
**Epic:** https://github.com/pheature-flags/pheature-flags/issues/22 Symfony Toggle
**Package:** https://github.com/pheature-flags/symfony-toggle

* Load [Toggle PSR-7 API](https://github.com/pheature-flags/toggle-crud-psr7-api)
* Load Toggle and [CRUD](https://github.com/pheature-flags/toggle-crud) services 
* Define default configs
* Check how to PR to https://github.com/symfony/recipes-contrib/pulls

**Example config:**

![image](https://user-images.githubusercontent.com/1093654/115974061-4b115980-a55a-11eb-8980-6a3013713ffb.png)

**Example Controller**
![image](https://user-images.githubusercontent.com/1093654/115974075-6ed49f80-a55a-11eb-8585-09af9a236bca.png)

**Comment by kpicaza** [comment]
I have this from a local proof of concept, it may help

````
parameters:
  pheature_flags:
    prefix: ''
    driver: dbal
    toggles: []

services:
  # API
  Pheature\Crud\Psr7\Toggle\GetFeatures:
    class: Pheature\Crud\Psr7\Toggle\GetFeatures
    arguments:
      - '@Pheature\Core\Toggle\Read\FeatureFinder'
      - '@Psr\Http\Message\ResponseFactoryInterface'
    tags: ['controller.service_arguments']

  Pheature\Crud\Psr7\Toggle\GetFeature:
    class: Pheature\Crud\Psr7\Toggle\GetFeature
    arguments:
      - '@Pheature\Core\Toggle\Read\FeatureFinder'
      - '@Psr\Http\Message\ResponseFactoryInterface'
    tags: ['controller.service_arguments']

  Pheature\Crud\Psr7\Toggle\PostFeature:
    class: Pheature\Crud\Psr7\Toggle\PostFeature
    arguments:
      - '@Pheature\Crud\Toggle\Handler\CreateFeature'
      - '@Psr\Http\Message\ResponseFactoryInterface'
    tags: ['controller.service_arguments']

  Pheature\Crud\Psr7\Toggle\PatchFeature:
    class: Pheature\Crud\Psr7\Toggle\PatchFeature
    arguments:
      - '@Pheature\Crud\Toggle\Handler\AddStrategy'
      - '@Pheature\Crud\Toggle\Handler\RemoveStrategy'
      - '@Pheature\Crud\Toggle\Handler\EnableFeature'
      - '@Pheature\Crud\Toggle\Handler\DisableFeature'
      - '@Psr\Http\Message\ResponseFactoryInterface'
    tags: ['controller.service_arguments']

  Pheature\Crud\Psr7\Toggle\DeleteFeature:
    class: Pheature\Crud\Psr7\Toggle\DeleteFeature
    arguments:
      - '@Pheature\Crud\Toggle\Handler\RemoveFeature'
      - '@Psr\Http\Message\ResponseFactoryInterface'
    tags: ['controller.service_arguments']

  # Command Handlers
  Pheature\Crud\Toggle\Handler\CreateFeature:
    class: Pheature\Crud\Toggle\Handler\CreateFeature
    arguments:
      - '@Pheature\Core\Toggle\Write\FeatureRepository'

  Pheature\Crud\Toggle\Handler\AddStrategy:
    class: Pheature\Crud\Toggle\Handler\AddStrategy
    arguments:
      - '@Pheature\Core\Toggle\Write\FeatureRepository'

  Pheature\Crud\Toggle\Handler\RemoveStrategy:
    class: Pheature\Crud\Toggle\Handler\RemoveStrategy
    arguments:
      - '@Pheature\Core\Toggle\Write\FeatureRepository'

  Pheature\Crud\Toggle\Handler\EnableFeature:
    class: Pheature\Crud\Toggle\Handler\EnableFeature
    arguments:
      - '@Pheature\Core\Toggle\Write\FeatureRepository'

  Pheature\Crud\Toggle\Handler\DisableFeature:
    class: Pheature\Crud\Toggle\Handler\DisableFeature
    arguments:
      - '@Pheature\Core\Toggle\Write\FeatureRepository'

  Pheature\Crud\Toggle\Handler\RemoveFeature:
    class: Pheature\Crud\Toggle\Handler\RemoveFeature
    arguments:
      - '@Pheature\Core\Toggle\Write\FeatureRepository'

  # Dbal Features
  Pheature\Dbal\Toggle\Read\DbalFeatureFactory:
    class: Pheature\Dbal\Toggle\Read\DbalFeatureFactory

  Pheature\Core\Toggle\Read\FeatureFinder:
    class: Pheature\Dbal\Toggle\Read\DbalFeatureFinder
    arguments:
      - '@doctrine.dbal.default_connection'
      - '@Pheature\Dbal\Toggle\Read\DbalFeatureFactory'

  Pheature\Core\Toggle\Write\FeatureRepository:
    class: Pheature\Dbal\Toggle\Write\DbalFeatureRepository
    arguments:
      - '@doctrine.dbal.default_connection'

  # Toggle
  Pheature\Core\Toggle\Read\Toggle:
    class: Pheature\Core\Toggle\Read\Toggle
    arguments:
      - '@Pheature\Core\Toggle\Read\FeatureFinder'

  # SDK
  Pheature\Sdk\CommandRunner:
    class: Pheature\Sdk\CommandRunner
    arguments:
      - '@Pheature\Core\Toggle\Read\Toggle'
````
